### ISSUE TITLE
Install.sh fails if unzip is not installed

### ISSUE THREAD

**Issue by NLstn** [denoland/deno_install#117]
If unzip is not installed, the install.sh should install it for you

**Comment by nayeemrmn** [comment]
No, but it should be documented in the README.

**Comment by MarkTiedemann** [comment]
Yep, this belongs in the "Known Issues" section of the README: https://github.com/denoland/deno_install#known-issues

**Comment by hardy613** [comment]
Hello, 
I ran into this issue installing deno inside docker, I believe we could use `tar` to make the install more portable. As I was just working on this I don't mind making a PR.

**Comment by Yamboy1** [comment]
I think part of this is because deno moved from a gzipped binary to a zip file. I remember having to update my aur package, and had to add unzip because I didn't realise that it wasn't part of base-devel (in arch) like gzip was. Can i ask why we removed that gzipped file? It was nice and easy to use imo

**Comment by hardy613** [comment]
We have updated the readme in the `known issues` section and moved program checks to the start of the file. 

@MarkTiedemann I believe it is reasonable to close this issue.
