### ISSUE TITLE
Add installer written in deno

### ISSUE THREAD

**Issue by ry** [denoland/deno_install#14]
If you have a prior version of Deno installed, it would be cool to upgrade using this:
```
> deno https://deno.land/x/install/install.ts 
```

**Comment by sh7dm** [comment]
Maybe add an installer written in Node too?

**Comment by gocs** [comment]
Add an Node installer written in deno.

**Comment by kostadinnm** [comment]
That would be a nice feature.
But, adoption-wise, wouldn't a better move be putting some efforts in issuing a flatpak app for the linux community?! Moreover, flatpak's app isolation lines up with the philosophical boundaries to accessing the system that deno has, right!?

**Comment by sh7dm** [comment]
As @kostadinnm suggested Flatpak, I suggest Snap too :)

**Comment by sh7dm** [comment]
@ry if you don't mind, I can try to create Deno snap.

**Comment by kt3k** [comment]
Probably solved by https://github.com/denoland/deno/pull/4328 ?

**Comment by coreybutler** [comment]
Just food for thought... does it _really_ make sense to write the installer in deno?

Early Windows adoption of Node was relatively poor/slow, primarily because the upgrade/downgrade process was hard/non-existant. nvmw was written with Node, which had a number of complications as the project grew, primarily because old versions of Node didn't have what was needed to properly upgrade. Things changed, as is the nature of tech. NVM for Windows and Nodist were far more successful in onboarding Windows users, primarily by removing their dependency on the runtime they're trying to install (both are Go-based).

Perhaps it would be better to just have a Rust-based installer, i.e. no explicit dependency on deno.

**Comment by MarkTiedemann** [comment]
@bartlomieju Wanna close this one? It's solved by `deno --upgrade`.
