### ISSUE TITLE
Change installation directory

### ISSUE THREAD

**Issue by ry** [denoland/deno_install#40]
Since https://github.com/denoland/deno/commit/e782ba1a6fd8342cddd961da9274dbd0244685d1  deno now stores cache files in platform dependent cache directories like `$HOME/Library/Caches` (mac).

Downloading the deno binary into `$HOME/.deno/bin` seems now inappropriate. 

Where should it be installed?

cc @flying-sheep

**Comment by MarkTiedemann** [comment]
On Windows, it should be `%APPDATA%`.

**Comment by flying-sheep** [comment]
The library we use has a function for that as well: `dirs::executable_dir()`. Sadly it returns `None` on macOS and Windows.

So there we should put it somewhere into `dirs::data_dir()` or `dirs::data_local_dir()`. (`%APPDATA%` is `dirs::data_dir()` on windows)

**Comment by MarkTiedemann** [comment]
- Which directory should be used on Linux?
- Should there be some clean-up logic in the installer scripts for a transition period? e.g. removing $HOME/.deno/bin from the $PATH as well as deleting the directory. Perhaps we can add the clean-up logic to the scripts temporarily for a few weeks, then remove it.

**Comment by ry** [comment]
I think clean up logic is overkill.
Not sure if there is some standard place to install local programs on Linux. I’ve always setup my own dir structure where I have $HOME/bin in my path...

**Comment by MarkTiedemann** [comment]
> I think clean up logic is overkill.

Agreed.

> Not sure if there is some standard place to install local programs on Linux. I’ve always setup my own dir structure where I have $HOME/bin in my path...

I've always used `/usr/bin`.

[soc/dirs-rs](https://github.com/soc/dirs-rs) uses `$XDG_BIN_HOME/../bin` or `$XDG_DATA_HOME/../bin` or `$HOME/.local/bin`. I think it's great that this crate follows both the [xdg-user-dirs](https://www.freedesktop.org/wiki/Software/xdg-user-dirs/) and the [systemd-file-hierarchy](https://www.freedesktop.org/software/systemd/man/file-hierarchy.html) spec. But pragmatically speaking, not everyone knows about or follows these specs. For example, on Alpine, none of the above locations are available so, stretching the point a bit, installing Deno would fail in half of all Docker images...

I'd love to run `/usr/bin/deno` on Linux and Mac (or just `deno` since it's already in the PATH) and `%APPDATA%\deno` on Windows (or just `deno` since we can easily add it to the PATH via [`Environment.SetEnvironmentVariable`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable#System_Environment_SetEnvironmentVariable_System_String_System_String_) as part of the installation script, as we currently do in the PowerShell installer).

**Comment by flying-sheep** [comment]
> I've always used `/usr/bin`.

That’s a path managed by your package manager. If you install a package using `yum`, `apt`, `pacman`, or something, that’s the path its binary/ies should end up in. If you use a script or do it manually, it depends:

- Systemwide installations go `/usr/local/` (binaries to `/usr/local/bin`, data files to `/usr/local/share`)
- Userwide installations go to `$XDG_*_HOME` (data files to `$XDG_DATA_HOME`, which defaults to `~/.local/share`)

    There’s no `$XDG_BIN_HOME`, but many linux distributions add `~/.local/bin` to `$PATH`, so I think it’s the best place. As you said, the Rust `dirs` library used by deno does `$XDG_DATA_HOME/../bin`

> For example, on Alpine, none of the above locations are available so, stretching the point a bit, installing Deno would fail in half of all Docker images...

I don’t understand. What’s the difference between `mkdir ~/.deno` and `mkdir -p ~/.local/bin`? Why would the latter fail while the former doesn’t?

---

I propose:

- A systemwide installation uses `/usr/local/bin/`
- A user installation uses `$XDG_BIN_HOME/../bin` or `$XDG_DATA_HOME/../bin` or `$HOME/.local/bin` and if it’s not in `$PATH`, will ask you to add it to `$PATH`.

**Comment by MarkTiedemann** [comment]
> > `%APPDATA%\deno`
>
> I’m not sure but I think Windows expects things to be in subfolders here. I’ve never seen any file directly in `%APPDATA%`

True, I slipped up there, the directory should be `%APPDATA%\deno`, the binary should be `%APPDATA%\deno\deno.exe`.

> Many Linux distributions have `~/.local/bin` in their `$PATH`

Many, but not all. That's exactly my point. I'd prefer to choose a location that is always in `$PATH` so we don't have to print a message asking the user to add the location to the `$PATH`.

>   * `$XDG_BIN_HOME` doesn’t exist, right?

Yes, the [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) doesn't mention anything in regards to binaries or executables. So yes, we can and should use it for the cache location, but it doesn't apply in this case.

>   * A systemwide installation
>   * A user installation
>   * There should also be a way to do a “chrooted system install” for package managers.

I think that's too complicated. I don't have much Linux experience, so maybe I'm completely off here (in which case, I'm sorry) but I'd like to have one place where I can find the deno binary no matter how it was installed.

Before, we'd have a README.md that said "installs binaries into `$HOME/.deno/bin`". That's very simple and easy to understand.

In my ideal world, the new README.md would say something along the lines of:

> After the installation, the Deno binaries can be found in the following locations:
>   - Linux & Mac: `/usr/local/bin/deno`
>   - Windows: `%APPDATA%\deno\deno.exe`

**Comment by flying-sheep** [comment]
> I'd prefer to choose a location that is always in `$PATH` so we don't have to print a message asking the user to add the location to the `$PATH`.

> I think that's too complicated. I don't have much Linux experience, so maybe I'm completely off here (in which case, I'm sorry) but I'd like to have one place where I can find the deno binary no matter how it was installed.

You are completely off, sorry. This is exactly how it should be. This part is not up for dicussion, it’s universally agreed upon:

- `/usr/{bin,share,lib,...}` is for the package manager. Users and admins are not to fuck around here since the package managers will be confused by or overwrite changes. Do not touch manually.
- For systemwide manual installation, there’s `/usr/local/bin`
- Users can’t write to system dirs. To be able to install their own software they’re able to do what they want in `$HOME`. Due to Python using it, `~/.local/bin` crystallized as a location for binaries that many distributions support. Others have *no user location* in their `$PATH`.

---

I think what would be easiest is to provide `--user` and `--prefix=...`.

- `./deno-install.sh --prefix=foo` installs to `foo/bin`
- `./deno-install.sh` would install as if `--prefix=/usr/local` was provided, and give a helpful error message pointing to `--user` and `sudo` if `/usr/local/bin` is not writable.
- `./deno-install.sh --user` is a shortcut for `./deno-install.sh --prefix=${XDG_DATA_HOME-$HOME/.local/share}/../bin`

Providing `--prefix` makes life easy for debian/arch/ubuntu/... maintainers to create a deno package. They simply add `./deno-install.sh --prefix=$pkgdir/usr/` to their package script instead of manually copying the binary from wherever it ends up.

**Comment by MarkTiedemann** [comment]
Thanks for the explanation, @flying-sheep.

My only remaining concern is about simplicity: Before, deno was in `$HOME/.deno/bin` no matter the platform. Now, we're dealing with different locations, user permissions, flags, specs, etc.

Is it really worth it?

For example, on Windows, moving from `$HOME` (`%HOMEDRIVE%%HOMEPATH%`) to `%APPDATA%` doesn't really change a thing.

> makes life easy for debian/arch/ubuntu/... maintainers

I'd like to think that this repo is for the average JavaScript dev that just wants to try out Deno. Linux maintainers aren't really the target audience, I'd say.

**Comment by flying-sheep** [comment]
No problem! I think there’s some necessary complexity, and some nice-to-have options.

I think allowing the choice between a user installation vs a system wide installation on all platforms is something a installer script should be able to do. Users want to install deno in their `$HOME` (where they have write access) and admins want to install it for all users.

If you agree, that would make at least two locations on at least one platform necessary complexity. On Linux, we have `/usr/local/bin`, `/usr/bin`, and often `$HOME/.local/bin` in the `$PATH`, so a choice between `/usr/local/bin` and `$HOME/.local/bin` seems like the best idea: It will just work™ for most people, and not mess with the package-manager-only nature of `/usr/bin`.

I think `--prefix` to help package maintainers is a nice-to-have, but worth a consideration *if* we can fit it organically into the installer CLI.

> For example, on Windows, moving from `$HOME` (`%HOMEDRIVE%%HOMEPATH%`) to `%APPDATA%` doesn't really change a thing.

But it does. It prevents `.deno` from appearing in the users home folder. Windows doesn’t have hidden dot directories in the home folder, it’s a weird and alien thing to do there.

In the windows world, there is no standard binary path, so it doesn’t matter where we install deno to – we’ll have to add it to `%PATH%` in any case. Here, too, there’s a user and a systemwide installation: Windows has user and system environment variables. Depending on which one we add deno’s bin folder to, all users or just the installing user will see it.

**Comment by MarkTiedemann** [comment]
> But it does. It prevents `.deno` from appearing in the users home folder.

At least on my Windows machine, there's already ~40 folders and files from various tools there. Now you could argue that's bad practice for those tools to put their dot files there, but you could also argue that, since it's already common practice, we might as well just accept it as the standard.

> I think allowing the choice between a user installation vs a system wide installation on all platforms is something a installer script should be able to do.

Agreed.

So `/usr/local/bin` for system install and `$HOME/.local/bin` for user install (with user install beeing the default).

On Windows, perhaps `%APPDATA%\deno\bin` for user install and `%ProgramFiles(x86)%\deno\bin` for system install.

What about Mac?

**Comment by MarkTiedemann** [comment]
I think, before we implement any of this, we should have a clear picture of where all deno files, not just the binary, are supposed to be located on all platforms.

(If we document this properly, perhaps in the manual, we'd enable people to completely remove deno from their system. Also, we could write the complementary uninstall script.)

**Comment by flying-sheep** [comment]
Of course! Is there any other file apart from the cache?

**Comment by MarkTiedemann** [comment]
There is the history file, `deno_history.txt`.

Are `deps/` and `gen/` both cache dirs?

Also, should we consider versioning in some form up front? Should people be able to install multiple versions of deno on the same machine in a standardized way? (Python using `~/.local/bin` may not be the best example here, on Windows they are using: `C:\Python27` `C:\Python33`...)

**Comment by flying-sheep** [comment]
I’ve [read a pretty good definition](https://ploum.net/207-modify-your-application-to-use-xdg-folders/) what belongs where:

> There’s a little trick : just imagine that it was deleted. What would you think as a user ?
> 
> If you would cry, running frenetically to your backup, it means that it belongs to XDG_DATA_HOME.
> 
> If you would think « Damn, I will have to reconfigure all », it belongs to $XDG_CONFIG_HOME. This includes user installed plugins even if those plugins might themselves have files in XDG_DATA_HOME. The exception I see is the usernames/passwords for external services. Those are clearly configuration stuffs but, imho, just fit better in XDG_DATA_HOME.
> 
> If you would just think « It’s bloody slow those days » then it is obviously part of XDG_CACHE_HOME.

Or in other words: Stuff that gets automatically recreated (which applies to `deps/` and `gen/`) goes to `XDG_CACHE_HOME`/`%LOCALAPPDATA%`/`~/Library/Caches`. I think `deno_history.txt` should go into `XDG_DATA_HOME`/`%APPDATA%`/`~/Library/Application Support`, since some people treat their shell histories as something like a snippet collection and would be sad if it gets autodeleted.

**Comment by MarkTiedemann** [comment]
> Please also note that all complexity is pretty much gone for the user if we just add a `deno --paths` command that prints the 4 paths of the binary, the history, `deps/` and `gen/`.

There is also complexity in needing, creating, and maintaining a command like this. But I agree with you in principle: we can make this user-friendly, even if it's not as friendly as `$HOME/.deno` on every system.

On another note, should we use `$XDG_CACHE_HOME/deno` in user installations and `/var/cache/deno` in system installations? (If we do that, this needs to be implemented in deno, not in this repo.)

**Comment by MarkTiedemann** [comment]
> Also, should we consider versioning in some form up front? Should people be able to install multiple versions of deno on the same machine in a standardized way?

Actually, I think it would be awesome if the scripts in this repo were just for bootstrapping deno, and deno, once installed for the first time, could update and manage multiple versions of itself. Or we transform this repo into something similar to rustup - perhaps deno_up? :)

**Comment by ry** [comment]
deps/ and gen/ are cache and should be stored in the cache dir. They are (as of v0.3.0) stored in the "proper" directories. Same with deno_history.txt  ... 

Let's not make this overly complicated. These install scripts are for local installations only - not system installs. For system installs people will use brew, apt, or scoop.

I'd like to see a 3x2 table with the bin dir and cache dir on each of the 3 platforms. It would be helpful to use display concrete examples instead of variables like `$XDG_CACHE_HOME`.

For what it's worth here is what my $PATH looks like on my macintosh: `/Users/rld/src/google-cloud-sdk/bin:/Users/rld/.nvm/versions/node/v10.14.2/bin:/Users/rld/.deno/bin:/usr/local/bin:/Users/rld/.cargo/bin:/Users/rld/.gem/ruby/2.3.0/bin:/Users/rld/bin:/Users/rld/.npm-packages/bin:/Users/rld/go/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/rld/src/deno/third_party/depot_tools`. There are no standard local directories.

Since, at least on my platform, running deno_install is going to require that I modify my path, I think I would like to keep it simple and just install the binary where the cache files are.

**Comment by ry** [comment]
> Actually, I think it would be awesome if the scripts in this repo were just for bootstrapping deno, and deno, once installed for the first time, could update and manage multiple versions of itself. Or we transform this repo into something similar to rustup - perhaps deno_up?

This is beyond the scope of deno. This deno_install script is meant to be the equivalent of rustup.

**Comment by flying-sheep** [comment]
> Let's not make this overly complicated. These install scripts are for local installations only - not system installs. For system installs people will use brew, apt, or scoop.

Very well. deno’s file structure is simple enough that packagers can easily manually do what they want.

> I'd like to see a 3x2 table with the bin dir and cache dir on each of the 3 platforms. It would be helpful to use display concrete examples instead of variables like `$XDG_CACHE_HOME`.

OK! Examples:

| | Windows | macOS | Linux
| --- | --- | --- | ---
| **bin dir** | `C:\Users\me\AppData\Roaming\deno\` | `/Users/me/Library/Application Support/deno` | `/home/me/.local/bin/`
| **cache dir** | `C:\Users\me\AppData\Local\deno\` | `/Users/me/Library/Caches/deno` | `/home/me/.cache/deno/`

Real logic, using the shell syntax of `${var_name-default_value}`:

| | Windows | macOS | Linux
| --- | --- | --- | ---
| **bin dir** | `%appdata%\deno\` | `$HOME/Library/Application Support/deno/` | `$HOME/.local/bin/`
| **cache dir** | `%localappdata%\deno\` | `$HOME/Library/Caches/deno/` | `${XDG_CACHE_HOME-$HOME/.cache}/deno/`

I’m not sure about the bin dir on macOS. I think we could follow Python’s lead if it offers a user install like it does on Windows. Could someone check?

> Since, at least on my platform, running deno_install is going to require that I modify my path, I think I would like to keep it simple and just install the binary where the cache files are.

Nope! That’s exactly not where it should go, since it’ll be deleted. Remember: All platforms have a cache dir that they can clean on will. Everything that gets autogenerated should definitely go there, and nothing else.

**Comment by ry** [comment]
I think `.local/bin` makes more sense than Application Support for OSX.

Cool thanks for clarifying this.

**Comment by MarkTiedemann** [comment]
Not quite sure about `$HOME/Library/Application Support/deno/`. At least on my Mac only GUI apps are using this directory. Most CLI apps are located in `/usr/local/bin/`.

Also, I'm not sure about `$HOME/Library/Caches/deno/`. Just found this goodie: `getconf DARWIN_USER_CACHE_DIR`. This prints `/var/folders/9q/gfr1_n0964d8x_0c5jm2t29c0000gn/C/` on my machine and contains far more folders than `$HOME/Library/Caches`.

**Comment by MarkTiedemann** [comment]
> I think `.local/bin` makes more sense than Application Support for OSX.

`~/.local/bin` doesn't even exist on my Mac. :S

**Comment by ry** [comment]
slightly better than $HOME/.deno at least it has the potential to overlap with existing $PATH setups.

**Comment by MarkTiedemann** [comment]
> at least it has the potential to overlap with existing $PATH setups.

I'd prefer `/usr/local/bin/` on Mac. Then no `$PATH` setup is needed at all. I believe this would be most user friendly.

**Comment by ry** [comment]
`/usr/local/bin` requires root

**Comment by flying-sheep** [comment]
OK, edited the post

**Comment by ry** [comment]
Cool - these values work for me. We should also add this table to the docs once we complete the transition.

**Comment by MarkTiedemann** [comment]
If the bin dir is `%APPDATA%\deno` on Windows, then we need to update the cache dir in deno first so the `\dep` and `\gen` cache dirs won't be placed in `%APPDATA%` directly. (Or are they not placed relative to the binary?)

@flying-sheep Would you implement the cache dir in deno? I'd implement the bin dir in deno_install then. :)

**Comment by flying-sheep** [comment]
> Would you implement the cache dir in deno?

I already did that in denoland/deno#1763, which sparked this discussion :sweat_smile:

> Or are they not placed relative to the binary?

They never(?) were! Before denoland/deno#1763, the cache dir was simply `~/.deno/`, independent of the binary location. [Now the code is](https://github.com/denoland/deno/blob/master/src/deno_dir.rs#L66-L73):

```rust
let home_dir = dirs::home_dir().expect("Could not get home directory.");
let fallback = home_dir.join(".deno");
let default = dirs::cache_dir()
    .map(|d| d.join("deno"))
    .unwrap_or(fallback);
```

**Comment by nayeemrmn** [comment]
@ry Do you still see this as a problem?

The only sensible alternative is `$XDG_BIN_HOME` (which exists now) and its fallback `~/.local/bin`. https://docs.rs/dirs/2.0.2/dirs/fn.executable_dir.html. As you can see, it isn't defined for macOS and Windows so they would have to fallback to `$HOME/.deno/bin` anyway. Actually there is some use of `~/.local/bin` on macOS but I don't know how correct it is.

**Comment by ry** [comment]
$XDG_BIN_HOME sounds better

**Comment by flying-sheep** [comment]
> The only sensible alternative is `$XDG_BIN_HOME` (which exists now)

Amazing, but I couldn’t find any source. Can you give us a link?
