### ISSUE TITLE
support chocolatey

### ISSUE THREAD

**Issue by ry** [denoland/deno_install#73]
https://chocolatey.org

**Comment by MarkTiedemann** [comment]
Haven't used Chocolatey in years (ever since I learned about [Scoop](https://scoop.sh/), which we already support...) so this isn't high priority to me.

@ry If you have any good reasons for why this is important, please let me know. I do have some free time coming up, so I might take a stab at creating the package in the next few days.

In any case, here's the documentation for creating a Chocolatey package:

- CreatePackagesQuickStart: https://chocolatey.org/docs/create-packages-quick-start
- CreatePackages: https://chocolatey.org/docs/create-packages

Unlike Scoop packages (e.g. [`deno.json`](https://github.com/ScoopInstaller/Main/blob/master/bucket/deno.json)), Chocolatey packages aren't updated automatically. So we'd have to do that as part of the Deno release process.

@ry You'll also need to register an account and manage the API key.

PS: To be completely honest, I don't think creating a Chocolatey package is worth it at this point...

**Comment by digitalcoyote** [comment]
I can build an automatically updating Chocolatey package (I have an AU repo). It should not require any changes to the current release process and I can add this project's maintainers as maintainers for the package if they have/create a Chocolatey account.

**Comment by ry** [comment]
@digitalcoyote That would be great

**Comment by digitalcoyote** [comment]
I've got a working auto-updating package ready, but I noticed that after installing, `deno --help` did not output a response (I double-checked the other install methods and this was true for the other install methods)

**Comment by ry** [comment]
@digitalcoyote We cannot repeat your "deno --help" problem. (cc @piscisaureus) 

![image](https://user-images.githubusercontent.com/80/67122594-29445300-f1bc-11e9-9ba0-7023f3437b52.png)

**Comment by digitalcoyote** [comment]
I was afraid it was something on my side. I'll troubleshoot my install and then verify the chocolatey package is installing correctly

**Comment by digitalcoyote** [comment]
I got it working on my end, and the package is public. I'll ready a PR with install directions.
https://chocolatey.org/packages/deno

**Comment by digitalcoyote** [comment]
If older versions need to be submitted, let me know. New versions should be published automatically.

**Comment by EvanHahn** [comment]
Chocolatey instructions were added to the readme several months ago in 75b6b476b57cc6d7d6a4f1e314a91a5fdb73c085. Should this issue be closed?

**Comment by Yamboy1** [comment]
@ry ^

**Comment by MarkTiedemann** [comment]
@bartlomieju This issue can be closed.
