### ISSUE TITLE
brew install deno needs Xcode, that's too big

### ISSUE THREAD

**Issue by xialvjun** [denoland/deno_install#79]
```
deno: A full installation of Xcode.app 10.0 is required to compile
this software. Installing just the Command Line Tools is not sufficient.
```

**Comment by xialvjun** [comment]
maybe we can offer a prebuilt version.

**Comment by ry** [comment]
The homebrew version of deno is prebuilt and doesn't require xcode. We also publish binaries [here](https://github.com/denoland/deno/releases).

**Comment by xialvjun** [comment]
@ry https://github.com/Homebrew/homebrew-core/blob/master/Formula/deno.rb

It's not. I don't know should I issue here or in homebrew.

**Comment by ry** [comment]
@xialvjun Oh then it's an error in the brew formula (which is maintained externally).

Summoning @chrmoritz : have you experienced this situation?

**Comment by chrmoritz** [comment]
@xialvjun You are using with macOS Sierra (10.12) an too old and unsupported version of macOS, for which homebrew doesn't provide any official bottles anymore. You could either try to use [the binary provided by deno for macOS](https://github.com/denoland/deno/releases/latest) or try to forcefully install the High Sierra bottle in homebrew, which might or might not work for you. 

If not, than you have no other option than trying to build it from source, which unfortunately requires full XCode (because of V8). 
*Note that you will likely have to `export FORCE_MAC_SDK_MIN="10.12"` too, because V8 doesn't official support Sierra (it's SDK) anymore either).*

**Comment by xialvjun** [comment]
Got it. I'll upgrade macos version to latest mojave.

**Comment by dwiyatci** [comment]
@xialvjun Just out of curiosity: are you still running Mojave (and has it been good)? Got the same problem today when trying to isntall deno from Homebrew– call me old-skool but I've been staying with El Capitan ever since I bought my last non-TouchBar MBP in late 2015 😅

**Comment by xialvjun** [comment]
@dwiyatci  Now I'm running BigSur. 
brew gives me a prebuilt version.
