### ISSUE TITLE
Install on macOs using homebrew?

### ISSUE THREAD

**Issue by osenvosem** [denoland/deno_install#8]
In would be reasonable to give users the opportunity to easily install deno on macOs using brew formula.

**Comment by wiesson** [comment]
I would appreciate that! 👏

**Comment by hayd** [comment]
https://github.com/Homebrew/homebrew-core/pull/35590

**Comment by ry** [comment]
Thanks for setting that up hayd!

**Comment by ry** [comment]
@hayd yeah that seems appropriate

**Comment by hayd** [comment]
My first binary-only was closed, though we could add that independently in this repo (so that you could install via `brew install denoland/deno_install/brew.rb`).

Trying to build with brew: https://github.com/Homebrew/homebrew-core/pull/35645
Note: there's an interesting error when testing locally - it builds fine - many linker errors and then a stack-trace test fails), will see if their CI can demonstrate the same... either way will likely report as a deno issue.

**Comment by hayd** [comment]
@ry any thoughts/pointers on these linking warnings  and the source_map test failure?
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/35808/version=high_sierra/console

**Comment by ry** [comment]
@hayd yes - it’s fixed with this PR
https://github.com/denoland/deno/pull/1439
Ill land soon.

**Comment by hayd** [comment]
Great! Are the linker warnings anything to worry about?

**Comment by ry** [comment]
@hayd merged. If it builds there’s nothing to worry about :)

**Comment by ry** [comment]
dup https://github.com/denoland/deno/issues/1486
